"""empty message

Revision ID: b9524dacd7e3
Revises: 591a66b18e9a
Create Date: 2018-12-12 18:27:04.873150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9524dacd7e3'
down_revision = '591a66b18e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_companies_company'), 'companies', ['company'], unique=True)
    op.drop_index('ix_companies_companyName', table_name='companies')
    op.drop_column('companies', 'companyName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('companyName', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_index('ix_companies_companyName', 'companies', ['companyName'], unique=True)
    op.drop_index(op.f('ix_companies_company'), table_name='companies')
    op.drop_column('companies', 'company')
    # ### end Alembic commands ###
